# Generated by Django 6.0.7 on 2026-08-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=models.ImageField(default='blog_images/default.png', upload_to='blog_images/'),
        ),
    ]
